name: Bug Report
description: File a bug report.
body:
  - type: markdown
    attributes:
      value: |
        Hi, here are some tips for reporting SDL bugs!

        - Are you here to ask a question? Consider [one of our communities](https://wiki.libsdl.org/SDL3/FAQCommunities) instead of the bug tracker.
        - [Are you sure it's an SDL bug?](https://wiki.libsdl.org/SDL3/HowToReportBugs#try-the-example-programs)
        - [Are you sure it's SDL's memory leak?](https://wiki.libsdl.org/SDL3/HowToReportBugs#reporting-memory-leaks)
        - [Tell us what platform you're using.](https://wiki.libsdl.org/SDL3/HowToReportBugs#tell-us-what-platform-youre-using)

        Thank you for helping make SDL better!
  - type: textarea
    id: what-happened
    attributes:
      label: Add a description.
      value: "Type your description here..."
    validations:
      required: false
